build:
  id: 201201
  version: 1.2.0.0
  name: "DEV-GIT-Development-build"
  type: "GIT Development Build"

spring:
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

management:
  endpoint:
    web:
      exposure:
        include: "*"
